### PR TITLE
Add basic typescript types file

### PR DESCRIPTION
**Pull request by luis-c465**
- Adds common node files and directories to gitignore
- Adds dependencies for generating typescript types [(`types.d.ts`)](https://github.com/luis-c465/p5.EasyCam/blob/add-typescript-support/types.d.ts)
- Adds npm command to generate types (`npm run generate-types`)
- Fixes issues where documentation above functions generated incorrect types
- Add typescript types file [(`types.d.ts`)](https://github.com/luis-c465/p5.EasyCam/blob/add-typescript-support/types.d.ts)

NOTE: Currently the types file is incomplete due to `p5.easycam.js` containing functions whose parameters are not documented

Fox example in the `zoom`method in the `EasyCam` class
https://github.com/freshfork/p5.EasyCam/blob/7ccafa88b957ebc3f0027e4a2976ae9afc8e97b7/p5.easycam.js#L719-L740

There is no documentation for the param `dz`

NOTE: Because of adding npm packages to the project `readme.md`should probably be updated to include installation of npm dependencies

### CODE REVIEW

**Comment by jwdunn1** [comment]
Thank you for the work here! Does this PR address issue #13? I need to test this branch before merging it. I'm somewhat new to the nodejs area. I've downloaded a copy of your dev branch, but I'm not sure what to do next. What are the npm dependencies for this and what is the command to add them? Do these changes allow someone to run the code on the node server?

**Comment by luis-c465** [comment]
Yes the idea behind this PR was to address the typescript support of issue #13.

---

The npm dependencies are located in the `package.json`:
https://github.com/freshfork/p5.EasyCam/blob/756fd4bbd6eaa07c04386758e747ba06233c2859/package.json#L1-L10

If [node.js](https://nodejs.org/en/download/) is downloaded then this command will download the dependencies for the project:
```bash
npm install
```

Once the dependencies are installed then the types can be generated with the command 
```bash
npm run generate-types
```
This will generate `types.d.ts` and give output in the terminal like the following if the command was successful
```bash
> generate-types
> jsdoc -t node_modules/tsd-jsdoc/dist p5.easycam.js -d .

[TSD-JSDoc] p5.easycam.js:33:6 Failed to find parent of doclet '<anonymous>~INFO' using memberof '<anonymous>', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1251:4 Failed to find parent of doclet '<anonymous>~Rotation' using memberof '<anonymous>', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1466:4 Failed to find parent of doclet '<anonymous>~Scalar' using memberof '<anonymous>', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1505:4 Failed to find parent of doclet '<anonymous>~Vec3' using memberof '<anonymous>', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1629:0 Failed to find parent of doclet '<anonymous>~EasyCam.INFO' using memberof '<anonymous>~EasyCam', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1683:2 Failed to find parent of doclet 'p5#createEasyCam' using memberof 'p5', this is likely due to invalid JSDoc.
[TSD-JSDoc] p5.easycam.js:1653:0 Unable to resolve type for Dw.ext.Rotation, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:1657:0 Unable to resolve type for Dw.ext.Vec3, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:1661:0 Unable to resolve type for Dw.ext.Scalar, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:976:2 Unable to resolve type for EasyCam#getRotationScale, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:980:2 Unable to resolve type for EasyCam#getPanScale, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:984:2 Unable to resolve type for EasyCam#getZoomScale, none specified in JSDoc. Defaulting to `any`.
[TSD-JSDoc] p5.easycam.js:988:2 Unable to resolve type for EasyCam#getWheelScale, none specified in JSDoc. Defaulting to `any`.
```

The warning and errors the command is outputting are due to missing comment documentation in `p5.easycam.js`

---

I am confused about the last thing you said 

> Do these changes allow someone to run the code on the node server?

Which node server are you talking about here?

**Comment by jwdunn1** [comment]
Thank you for the clarification. [Apologies for my naivete. Most of my work is on the browser side in OpenProcessing.] I'm trying to understand the overall purpose of this branch. I guess I don't understand the "use case". My limited understanding of nodejs is simply: "Node is a server-side Javascript interpreter." If it is server-side, how do the p5js and EasyCam libraries fit in and what is the purpose of adding typescript support? Perhaps the functions whose parameters are not documented need to be fixed as part of this PR?

**Comment by luis-c465** [comment]
Node js is being used to run javascript without a browser to generate the types for `p5.easycam.js`. Node fits in as usually for javascript libraries there is  a file which contains the types the libraries functions and classes use as well as any documentation with the function or class. Node here enables the packages to be run locally to generate the types for the library.

For example p5.js has [installable types](https://www.npmjs.com/package/@types/p5) which then gives intellisense for all p5 functions and classes

---

<p align = "center">

</p>
<p align = "center">
intellisense for p5 function createCanvas in the code editor visual studio code
</p>

---

<p align = "center">

</p>
<p align = "center">
intellisense for p5.EasyCam function setViewport in the code editor visual studio code with <code>types.d.ts</code>
</p>

---

Overall the purpose of adding types is to make working with p5.EasyCam easier as instead of having to open a seperate window to read about the documentation of the functions and classes it could be read inside of the code editor.

And for those that want to use this library with typescript (javascript with optional types, typecheching, and other features) would be able to do so much easier and would be able to know that the functions are receiving the valid types

---

<p align = "center">

</p>
<p align = "center">
visual studio code reporting an error with input parameters for the function `EasyCam.setViewport`
</p>


---

Yeah, functions like `zoom` and others who don't have their parameters documented will need to have those added as part of the pull request as  currently the types file is missing the documentation some parameters

**Comment by jwdunn1** [comment]
Great explanation...now I grok it! Thanks for the patience. I was able to test the IntelliSense successfully in VS Code. I'll go ahead with the merge and delay the one-off fixes (i.e. the readme and the missing function types) as another PR.

**Pull request merged**
